version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=hello_go_todo
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
